logging:
  version: 1
  disable_existing_loggers: True
  formatters:
    simple:
      format: "[%(name)s] %(message)s"
  handlers:
    console:
      level: DEBUG
      formatter: simple
      class: logging.StreamHandler
      stream: "ext://sys.stdout"
  root:
    handlers:
      - console
    level: DEBUG
    propagate: False

hardware:
  main_camera: 0
  documents_camera: 1

passport_check:
  show_dev_tools: False



