logging:
  version: 1
  disable_existing_loggers: True
  formatters:
    simple:
      format: "[%(name)s] %(message)s"
  handlers:
    console:
      level: DEBUG
      formatter: simple
      class: logging.StreamHandler
      stream: "ext://sys.stdout"
  root:
    handlers:
      - console
    level: DEBUG
    propagate: False
  loggers:
    websockets.server:
      handlers:
        - console
      level: "ERROR"
    urllib3.connectionpool:
      level: WARNING

resources_dir: "../resources"
data_dir: "data"

hardware:
  main_camera: 0
  main_camera_resolution: 640x480
  documents_camera: 1
  dummy_robot: False
  serial: /dev/ttyTHS1


route:
  boarding_duration: 15
  service_duration: 300

server:
  host: "http://server:8002/"
  polling_interval: 5
  web_domain: "http://server:8002/static/"

gui:
  loading_page: "loading"
